import Head from 'next/head'
import React from 'react'

interface props {
  children: any;
  title: string;
}

export const HeadLayoutOne = ({children, title}:props) => {
  return (
    <>
      <Head>
        <title>{title? title : "IMM"}</title>
        <meta name="IMM-INDEX" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>

      {children}
    </>
  )
}
